// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuK6P-IzA0DUrPEoB6plVbwHTPGyNn72A',
    appId: '1:51382657466:web:ce66134e76103590663d83',
    messagingSenderId: '51382657466',
    projectId: 'loginauth-262df',
    authDomain: 'loginauth-262df.firebaseapp.com',
    storageBucket: 'loginauth-262df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqgrEdGY4_pvM0QxUkM2xlmc_EYNQEaTI',
    appId: '1:51382657466:android:bc64012a1def66dd663d83',
    messagingSenderId: '51382657466',
    projectId: 'loginauth-262df',
    storageBucket: 'loginauth-262df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASyZM_HZQWszsfL8om_0-DDMZiQHs-l9k',
    appId: '1:51382657466:ios:ff7aaa936ffd2358663d83',
    messagingSenderId: '51382657466',
    projectId: 'loginauth-262df',
    storageBucket: 'loginauth-262df.appspot.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASyZM_HZQWszsfL8om_0-DDMZiQHs-l9k',
    appId: '1:51382657466:ios:230a866262c8b339663d83',
    messagingSenderId: '51382657466',
    projectId: 'loginauth-262df',
    storageBucket: 'loginauth-262df.appspot.com',
    iosBundleId: 'com.example.loginAuth.RunnerTests',
  );
}
